<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="base_length" value="0.1" />
    <xacro:property name="base_width" value="0.1" />
    <xacro:property name="base_height" value="0.1" />

    <link name="base_footprint">
    </link>

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 0" rpy="0 0 0" />
    </joint>

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="100.0" l="${2*base_length}" w="${2*base_width}" h="${2*base_height}" 
                           xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
    </link>

    
    <!-- virtual arm base link on top of robot base_link -->
    <!-- <link name="virtual_arm_base_link">
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <mass value="1.5363204791731" />
            <inertia
                ixx="0.242660790998556"
                ixy="-9.00009815481889E-05"
                ixz="0.0234683038167963"
                iyy="0.514730499629884"
                iyz="2.70300300277055E-11"
                izz="0.664242254581203" />
        </inertial>
    </link>

    <joint name="base_virtual_joint" type="fixed">
        <parent link="base_link" />
        <child link="virtual_arm_base_link" />
        <origin xyz="0 0 ${base_height}" rpy="0 0 0" />
    </joint> -->

    

    <!--Arm Base Link -->
    <link name="arm_base_link">
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <mass value="100.5363204791731" />
            <inertia
                ixx="0.242660790998556"
                ixy="-9.00009815481889E-05"
                ixz="0.0234683038167963"
                iyy="0.514730499629884"
                iyz="2.70300300277055E-11"
                izz="0.664242254581203" />
        </inertial>
        <visual>
            <origin xyz="0 0 0"
                    rpy="0 0 0" />
            <geometry>
                <mesh filename="${mesh_location}/arm_base.stl" />
            </geometry>
            <material
                name="">
                <color rgba="1 1 1 1" />
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 0"
                    rpy="0 0 0" />
            <geometry>
                <mesh filename="${mesh_location}/arm_base.stl" />
            </geometry>
        </collision>
    </link>

    <joint name="arm_base_joint" type="revolute">
        <parent link="base_link"/>
        <child link="arm_base_link"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <limit effort="500" velocity="1.0" lower="-3.14" upper="3.14"/>
        <dynamics damping="10" friction="2"/>
    </joint>

    <!--Arm Shoulder Link -->
    <link name="arm_shoulder_link">
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <mass value="1.5363204791731" />
            <inertia
                ixx="0.242660790998556"
                ixy="-9.00009815481889E-05"
                ixz="0.0234683038167963"
                iyy="0.514730499629884"
                iyz="2.70300300277055E-11"
                izz="0.664242254581203" />
        </inertial>
        <visual>
            <origin xyz="0 0 0"
                    rpy="0 0 0" />
            <geometry>
                <mesh filename="${mesh_location}/arm_shoulder.stl" />
            </geometry>
            <material
                name="">
                <color rgba="1 1 1 1" />
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 0"
                    rpy="0 0 0" />
            <geometry>
                <mesh filename="${mesh_location}/arm_shoulder.stl" />
            </geometry>
        </collision>
    </link>

    <joint name="arm_shoulder_joint" type="revolute">
        <parent link="arm_base_link"/>
        <child link="arm_shoulder_link"/>
        <origin xyz="0.0 0.0 0.2104" rpy="0.0 0.0 0.0"/>
        <axis xyz="1 0 0"/>
        <limit effort="500" velocity="1.0" lower="-1.918" upper="1.918"/>
        <dynamics damping="10" friction="2"/>
    </joint>

    <!--Arm Elbow Link -->
    <link name="arm_elbow_link">
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <mass value="1.5363204791731" />
            <inertia
                ixx="0.242660790998556"
                ixy="-9.00009815481889E-05"
                ixz="0.0234683038167963"
                iyy="0.514730499629884"
                iyz="2.70300300277055E-11"
                izz="0.664242254581203" />
        </inertial>
        <visual>
            <origin xyz="0 0 0"
                    rpy="0 0 0" />
            <geometry>
                <mesh filename="${mesh_location}/arm_elbow.stl" />
            </geometry>
            <material
                name="">
                <color rgba="1 1 1 1" />
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 0"
                    rpy="0 0 0" />
            <geometry>
                <mesh filename="${mesh_location}/arm_elbow.stl" />
            </geometry>
        </collision>
    </link>

    <joint name="arm_elbow_joint" type="revolute">
        <parent link="arm_shoulder_link"/>
        <child link="arm_elbow_link"/>
        <origin xyz="0.0 0.0 0.4186" rpy="0.0 0.0 0.0"/>
        <axis xyz="1 0 0"/>
        <limit effort="500" velocity="1.0" lower="-1.748" upper="1.748"/>
        <dynamics damping="10" friction="2"/>
    </joint>

    <!--Arm Wrist Link -->
    <link name="arm_wrist_link">
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <mass value="1.5363204791731" />
            <inertia
                ixx="0.242660790998556"
                ixy="-9.00009815481889E-05"
                ixz="0.0234683038167963"
                iyy="0.514730499629884"
                iyz="2.70300300277055E-11"
                izz="0.664242254581203" />
        </inertial>
        <visual>
            <origin xyz="0 0 0"
                    rpy="0 0 0" />
            <geometry>
                <mesh filename="${mesh_location}/arm_wrist.stl" />
            </geometry>
            <material
                name="">
                <color rgba="1 1 1 1" />
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 0"
                    rpy="0 0 0" />
            <geometry>
                <mesh filename="${mesh_location}/arm_wrist.stl" />
            </geometry>
        </collision>
    </link>

    <joint name="arm_wrist_joint" type="revolute">
        <parent link="arm_elbow_link"/>
        <child link="arm_wrist_link"/>
        <origin xyz="0.0 0.0 0.4159" rpy="0.0 0.0 0.0"/>
        <axis xyz="1 0 0"/>
        <limit effort="500" velocity="1.0" lower="-1.942" upper="1.942"/>
        <dynamics damping="10" friction="2"/>
    </joint>

    <!--Arm gripper base Link -->
    <link name="arm_gripper_base_link">
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <mass value="1.5363204791731" />
            <inertia
                ixx="0.242660790998556"
                ixy="-9.00009815481889E-05"
                ixz="0.0234683038167963"
                iyy="0.514730499629884"
                iyz="2.70300300277055E-11"
                izz="0.664242254581203" />
        </inertial>
        <visual>
            <origin xyz="0 0 0"
                    rpy="0 0 0" />
            <geometry>
                <mesh filename="${mesh_location}/gripper_base.stl" />
            </geometry>
            <material
                name="">
                <color rgba="1 1 1 1" />
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 0"
                    rpy="0 0 0" />
            <geometry>
                <mesh filename="${mesh_location}/gripper_base.stl" />
            </geometry>
        </collision>
    </link>

    <joint name="arm_gripper_base_joint" type="revolute">
        <parent link="arm_wrist_link"/>
        <child link="arm_gripper_base_link"/>
        <origin xyz="0.05655 0.0 0.1025" rpy="0.0 0.0 0.0"/>
        <axis xyz="0 0 1"/>
        <limit effort="500" velocity="1.0" lower="-1.57" upper="1.57"/>
        <dynamics damping="10" friction="2"/>
    </joint>


    <!--Arm gripper left Link -->
    <link name="arm_gripper_left_link">
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <mass value="1.5363204791731" />
            <inertia
                ixx="0.242660790998556"
                ixy="-9.00009815481889E-05"
                ixz="0.0234683038167963"
                iyy="0.514730499629884"
                iyz="2.70300300277055E-11"
                izz="0.664242254581203" />
        </inertial>
        <visual>
            <origin xyz="0 0 0"
                    rpy="0 0 0" />
            <geometry>
                <mesh filename="${mesh_location}/gripper_left.stl" />
            </geometry>
            <material
                name="">
                <color rgba="1 1 1 1" />
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 0"
                    rpy="0 0 0" />
            <geometry>
                <mesh filename="${mesh_location}/gripper_left.stl" />
            </geometry>
        </collision>
    </link>

    <joint name="arm_gripper_left_joint" type="prismatic">
        <parent link="arm_gripper_base_link"/>
        <child link="arm_gripper_left_link"/>
        <origin xyz="-0.1393 0.0 0.06453" rpy="0.0 0.0 0.0"/>
        <axis xyz="1 0 0"/>
        <limit effort="500" velocity="1.0" lower="0.0" upper="0.08925"/>
        <dynamics damping="10" friction="2"/>
    </joint>

    <!--Arm gripper right Link -->
    <link name="arm_gripper_right_link">
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <mass value="1.5363204791731" />
            <inertia
                ixx="0.242660790998556"
                ixy="-9.00009815481889E-05"
                ixz="0.0234683038167963"
                iyy="0.514730499629884"
                iyz="2.70300300277055E-11"
                izz="0.664242254581203" />
        </inertial>
        <visual>
            <origin xyz="0 0 0"
                    rpy="0 0 0" />
            <geometry>
                <mesh filename="${mesh_location}/gripper_right.stl" />
            </geometry>
            <material
                name="">
                <color rgba="1 1 1 1" />
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 0"
                    rpy="0 0 0" />
            <geometry>
                <mesh filename="${mesh_location}/gripper_right.stl" />
            </geometry>
        </collision>
    </link>

    <joint name="arm_gripper_right_joint" type="prismatic">
        <parent link="arm_gripper_base_link"/>
        <child link="arm_gripper_right_link"/>
        <origin xyz="0.1393 0.0 0.06453" rpy="0.0 0.0 0.0"/>
        <axis xyz="-1 0 0"/>
        <limit effort="500" velocity="1.0" lower="0.0" upper="0.08925"/>
        <dynamics damping="10" friction="2"/>
        <mimic joint="arm_gripper_left_joint" multiplier="1.0" offset="0.0"/>
    </joint>
    

    
</robot>